server:
  port: ${SERVER_PORT:9000}

management:
  server:
    port: ${MANAGEMENT_PORT:8900}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  build:
    name: @project.name@
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@

spring:
  application:
    name: '@application.name@'

kafka-producer:
  kafka:
    topic: ${MESSAGE_TOPIC:message}
    replicaSize: ${REPLICA_SIZE:1}
    partitionSize: ${PARTITION_SIZE:4}
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:29092}